version: "3.8"

services:
  # 1. Servicio de Votación (Frontend)
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 2

  # 2. Servicio de Redis (Cola de votos)
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1

  # 3. Servicio de Worker (Procesador)
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1

  # 4. Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    deploy:
      replicas: 1

  # 5. Servicio de Resultados (Backend-UI)
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - backend
    deploy:
      replicas: 1

# Definición de Redes
networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

# Definición del Volumen
volumes:
  db-data: